server:
  port: ${PORT:8082}

spring:
  application:
    name: redis-api
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: ITEM_USER
    password: PASSWORD
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
    property-naming-strategy: SNAKE_CASE
  cache:
    type: redis
    redis:
      time-to-live: 2m
  redis:
    host: localhost
    port: 6379
    timeout: 1s

logging:
  level:
    me:
      hl: DEBUG
    org:
      springframework:
        cache: #Set 'TRACE' to enable cache log detail
