version: "3.5"
services:
  redis:
    container_name: redis_container
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  mysql:
    container_name: mysql_container
    image: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: ${MYSQL_USER:-ITEM_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - '3306:3306'
    restart: unless-stopped